apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://pkgs.tailscale.com/helmcharts
    chart: tailscale-operator
    targetRevision: 1.78.3
    helm:
      valuesObject:
        # Use existing secret for OAuth credentials
        # Create secret first: kubectl create secret generic operator-oauth \
        #   --namespace=tailscale-operator \
        #   --from-literal=client_id=YOUR_CLIENT_ID \
        #   --from-literal=client_secret=YOUR_CLIENT_SECRET
        oauth:
          clientId: ""
          clientSecret: ""
        operatorConfig:
          hostname: "arr-stack-k8s"
          # Empty string to disable tags (they must be defined in Tailscale ACLs first)
          defaultTags: ""
        proxyConfig:
          defaultTags: ""
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
