{{- if .Values.prowlarr.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "arr-stack.componentName" (dict "component" "prowlarr" "context" .) }}
  labels:
    {{- include "arr-stack.labels" . | nindent 4 }}
    {{- include "arr-stack.componentLabels" "prowlarr" | nindent 4 }}
spec:
  type: {{ .Values.prowlarr.service.type }}
  ports:
  - port: {{ .Values.prowlarr.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "arr-stack.selectorLabels" . | nindent 4 }}
    {{- include "arr-stack.componentLabels" "prowlarr" | nindent 4 }}
{{- end }}
